import { describe, it, expect } from 'vitest';
import {
  generateHardhatConfig,
  generateDeployScript,
  generateReadme,
} from '../../lib/scaffold/config-generator';
import type { ScaffoldConfig } from '../../lib/scaffold/types';

describe('Config Generator', () => {
  const mockConfig: ScaffoldConfig = {
    contractType: 'ERC20',
    name: 'MyToken',
    symbol: 'MTK',
    features: {
      mintable: true,
      burnable: false,
      pausable: true,
      permit: false,
      votes: false,
    },
    accessControl: 'ownable',
    pvmOptions: {
      resolcCompatible: true,
      twoStepDeploy: true,
      xcmHooks: false,
    },
  };

  describe('generateHardhatConfig', () => {
    it('should generate valid Hardhat config with resolc plugin', () => {
      const config = generateHardhatConfig(mockConfig);
      
      expect(config).toBeTruthy();
      expect(config).toContain("import '@parity/hardhat-resolc'");
      expect(config).toContain('resolc:');
      expect(config).toContain('compilerSource: \'npm\'');
      expect(config).toContain('polkadotHubTestnet:');
      expect(config).toContain('localhost:');
    });

    it('should include environment variable references for RPC and private key', () => {
      const config = generateHardhatConfig(mockConfig);
      
      expect(config).toContain('process.env.POLKADOT_HUB_TESTNET_RPC');
      expect(config).toContain('process.env.PRIVATE_KEY');
    });

    it('should include solidity version 0.8.24', () => {
      const config = generateHardhatConfig(mockConfig);
      
      expect(config).toContain('solidity: \'0.8.24\'');
    });

    it('should include comment about resolc plugin for PolkaVM', () => {
      const config = generateHardhatConfig(mockConfig);
      
      expect(config).toContain('// PVMforge: resolc plugin for PolkaVM compilation');
    });
  });

  describe('generateDeployScript', () => {
    it('should generate valid deploy script with two-step deployment comment', () => {
      const script = generateDeployScript(mockConfig);
      
      expect(script).toBeTruthy();
      expect(script).toContain('// PVMforge: Two-step PolkaVM deployment');
      expect(script).toContain('// Step 1: Upload code hash to chain');
      expect(script).toContain('// Step 2: Instantiate contract referencing uploaded hash');
    });

    it('should include contract name in deployment message', () => {
      const script = generateDeployScript(mockConfig);
      
      expect(script).toContain('Deploying MyToken to PolkaVM...');
      expect(script).toContain('MyToken deployed to:');
    });

    it('should use contract factory with contract name', () => {
      const script = generateDeployScript(mockConfig);
      
      expect(script).toContain("await ethers.getContractFactory('MyToken')");
    });

    it('should include deployer address logging', () => {
      const script = generateDeployScript(mockConfig);
      
      expect(script).toContain('Deployer:');
      expect(script).toContain('deployer.address');
    });

    it('should include waitForDeployment call', () => {
      const script = generateDeployScript(mockConfig);
      
      expect(script).toContain('await contract.waitForDeployment()');
    });

    it('should include error handling with process.exitCode', () => {
      const script = generateDeployScript(mockConfig);
      
      expect(script).toContain('process.exitCode = 1');
    });

    it('should include comment about resolc handling code upload', () => {
      const script = generateDeployScript(mockConfig);
      
      expect(script).toContain('// Step 1: Upload code (resolc handles this automatically with \'new\' keyword)');
    });
  });

  describe('generateReadme', () => {
    it('should generate README with contract details', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toBeTruthy();
      expect(readme).toContain('# MyToken — PVM Deployment Guide');
      expect(readme).toContain('**Type**: ERC20');
      expect(readme).toContain('**Symbol**: MTK');
      expect(readme).toContain('**Access Control**: ownable');
    });

    it('should include PVMforge attribution', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toContain('Generated by PVMforge');
      expect(readme).toContain('OZ v5.x');
      expect(readme).toContain('resolc compiler');
    });

    it('should include two-step deployment explanation', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toContain('Two-Step Deployment Note');
      expect(readme).toContain('1. Code upload: Contract bytecode is uploaded to the chain as a hash');
      expect(readme).toContain('2. Instantiation: Contract is created by referencing the uploaded code hash');
    });

    it('should include deployment commands with environment variables', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toContain('POLKADOT_HUB_TESTNET_RPC=<rpc_url> PRIVATE_KEY=<key>');
      expect(readme).toContain('npx hardhat run scripts/deploy.ts --network polkadotHubTestnet');
    });

    it('should include compilation command', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toContain('npx hardhat compile');
      expect(readme).toContain('# Uses resolc for PVM compilation');
    });

    it('should include resource links', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toContain('[Polkadot Hub Docs](https://docs.polkadot.com/smart-contracts/)');
      expect(readme).toContain('[PVMforge](https://pvmforge.dev)');
    });

    it('should display compatibility warnings when issues are present', () => {
      const issues = [
        { code: 'PVM_W001', message: 'Warning: Some feature may not work' },
        { code: 'PVM_E001', message: 'Error: Incompatible pattern detected' },
      ];
      const readme = generateReadme(mockConfig, issues);
      
      expect(readme).toContain('## PVM Compatibility Notes');
      expect(readme).toContain('**PVM_W001**: Warning: Some feature may not work');
      expect(readme).toContain('**PVM_E001**: Error: Incompatible pattern detected');
    });

    it('should filter out info-level issues from warnings list', () => {
      const issues = [
        { code: 'PVM_I001', message: 'Info: This is just informational' },
        { code: 'PVM_W001', message: 'Warning: This should appear' },
      ];
      const readme = generateReadme(mockConfig, issues);
      
      expect(readme).toContain('**PVM_W001**: Warning: This should appear');
      expect(readme).not.toContain('PVM_I001');
    });

    it('should display "No compatibility issues detected" when no issues', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toContain('No compatibility issues detected.');
    });
  });

  describe('Edge Cases', () => {
    it('should handle Governor contract type', () => {
      const govConfig: ScaffoldConfig = {
        ...mockConfig,
        contractType: 'Governor',
        name: 'MyDAO',
      };
      const readme = generateReadme(govConfig, []);
      
      expect(readme).toContain('**Type**: Governor');
      expect(readme).toContain('# MyDAO — PVM Deployment Guide');
    });

    it('should handle ERC721 contract type', () => {
      const nftConfig: ScaffoldConfig = {
        ...mockConfig,
        contractType: 'ERC721',
        name: 'MyNFT',
        symbol: 'NFT',
      };
      const readme = generateReadme(nftConfig, []);
      
      expect(readme).toContain('**Type**: ERC721');
      expect(readme).toContain('**Symbol**: NFT');
    });

    it('should handle roles access control', () => {
      const rolesConfig: ScaffoldConfig = {
        ...mockConfig,
        accessControl: 'roles',
      };
      const readme = generateReadme(rolesConfig, []);
      
      expect(readme).toContain('**Access Control**: roles');
    });

    it('should handle empty issues array', () => {
      const readme = generateReadme(mockConfig, []);
      
      expect(readme).toContain('No compatibility issues detected.');
    });

    it('should handle issues with only info codes', () => {
      const infoOnlyIssues = [
        { code: 'PVM_I001', message: 'Info message' },
        { code: 'PVM_I002', message: 'Another info' },
      ];
      const readme = generateReadme(mockConfig, infoOnlyIssues);
      
      expect(readme).toContain('No compatibility issues detected.');
    });
  });
});
