import type { ScaffoldConfig } from './types';

export function generateHardhatConfig(config: ScaffoldConfig): string {
  return `import { HardhatUserConfig } from 'hardhat/config';
import '@nomicfoundation/hardhat-toolbox';
// PVMforge: resolc plugin for PolkaVM compilation
import '@parity/hardhat-resolc';

const config: HardhatUserConfig = {
  solidity: '0.8.24',
  resolc: {
    compilerSource: 'npm', // uses @parity/resolc npm package
  },
  networks: {
    polkadotHubTestnet: {
      url: process.env.POLKADOT_HUB_TESTNET_RPC || '',
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
    },
    localhost: {
      url: 'http://localhost:8545',
    },
  },
};

export default config;
`;
}

export function generateDeployScript(config: ScaffoldConfig): string {
  return `import { ethers } from 'hardhat';

// PVMforge: Two-step PolkaVM deployment
// Step 1: Upload code hash to chain
// Step 2: Instantiate contract referencing uploaded hash
async function main() {
  console.log('Deploying ${config.name} to PolkaVM...');
  
  const [deployer] = await ethers.getSigners();
  console.log('Deployer:', deployer.address);

  // Step 1: Upload code (resolc handles this automatically with 'new' keyword)
  const Factory = await ethers.getContractFactory('${config.name}');
  
  // Step 2: Instantiate
  const contract = await Factory.deploy();
  await contract.waitForDeployment();
  
  console.log('${config.name} deployed to:', await contract.getAddress());
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
`;
}

export function generateReadme(config: ScaffoldConfig, issues: { code: string; message: string }[]): string {
  const warningsList = issues.filter(i => i.code.startsWith('PVM_W') || i.code.startsWith('PVM_E'))
    .map(i => `- **${i.code}**: ${i.message}`)
    .join('\n');

  return `# ${config.name} — PVM Deployment Guide
Generated by PVMforge | OZ v5.x | resolc compiler

## Contract
- **Type**: ${config.contractType}
- **Symbol**: ${config.symbol}
- **Access Control**: ${config.accessControl}

## PVM Compatibility Notes
${warningsList || 'No compatibility issues detected.'}

## Deployment Steps

### Prerequisites
\`\`\`bash
npm install
npx hardhat compile  # Uses resolc for PVM compilation
\`\`\`

### Deploy to Polkadot Hub Testnet
\`\`\`bash
POLKADOT_HUB_TESTNET_RPC=<rpc_url> PRIVATE_KEY=<key> npx hardhat run scripts/deploy.ts --network polkadotHubTestnet
\`\`\`

### Two-Step Deployment Note
PolkaVM uses a two-step deployment model:
1. Code upload: Contract bytecode is uploaded to the chain as a hash
2. Instantiation: Contract is created by referencing the uploaded code hash

The resolc compiler and \`@parity/hardhat-resolc\` handle this automatically.

## Resources
- [Polkadot Hub Docs](https://docs.polkadot.com/smart-contracts/)
- [PVMforge](https://pvmforge.dev)
`;
}
